export PATH=$HOME/.local/bin:$HOME/bin:/usr/local/bin:$HOME/.cargo/env:$PATH

# oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""
plugins=(git)
source $ZSH/oh-my-zsh.sh

# User configuration
export EDITOR='nvim'

# Typewritten theme/prompt
fpath+=$HOME/.zsh/typewritten
autoload -U promptinit; promptinit
prompt typewritten
export TYPEWRITTEN_PROMPT_LAYOUT="singleline"
export TYPEWRITTEN_LEFT_PROMPT_PREFIX_FUNCTION=(date +"%T")
